COUNTRIES = {
    'AF': 'minecraft:red_banner{Patterns:[{Pattern:"ts",Color:15},{Pattern:"bs",Color:13},{Pattern:"flo",Color:0},{Pattern:"mc",Color:14}]}',  # Afghanistan,
    'AL': 'minecraft:black_banner{Patterns:[{Pattern:"ss",Color:14},{Pattern:"ms",Color:15},{Pattern:"bo",Color:14},{Pattern:"ts",Color:14},{Pattern:"bs",Color:14}]}',  # Albania,
    'DZ': 'minecraft:green_banner{Patterns:[{Pattern:"hhb",Color:0},{Pattern:"flo",Color:14},{Pattern:"bt",Color:0}]}',  # Algeria,
    # 'AS': ''  # American Samoa,
    'AD': 'minecraft:yellow_banner{Patterns:[{Pattern:"mr",Color:14},{Pattern:"flo",Color:1},{Pattern:"bo",Color:4},{Pattern:"ts",Color:11},{Pattern:"bs",Color:14}]}',  # Andorra,
    'AO': 'minecraft:black_banner{Patterns:[{Pattern:"vhr",Color:14},{Pattern:"flo",Color:4}]}',  # Angola,
    # 'AI': ''  # Anguilla,
    # 'AQ': ''  # Antarctica,
    'AG': 'minecraft:black_banner{Patterns:[{Pattern:"flo",Color:4},{Pattern:"ld",Color:14},{Pattern:"lud",Color:14},{Pattern:"mr",Color:3},{Pattern:"mc",Color:0}]}',  # Antigua And Barbuda,
    'AR': 'minecraft:white_banner{Patterns:[{Pattern:"mc",Color:1},{Pattern:"flo",Color:4},{Pattern:"ts",Color:0},{Pattern:"bs",Color:0},{Pattern:"rs",Color:3},{Pattern:"ls",Color:3}]}',  # Argentina,
    'AM': 'minecraft:blue_banner{Patterns:[{Pattern:"rs",Color:14},{Pattern:"ls",Color:1}]}',  # Armenia,
    # 'AW': ''  # Aruba,
    'AU': 'minecraft:blue_banner{Patterns:[{Pattern:"tr",Color:0},{Pattern:"tr",Color:11},{Pattern:"dls",Color:0},{Pattern:"cr",Color:14},{Pattern:"vh",Color:11},{Pattern:"hhb",Color:11},{Pattern:"moj",Color:0},{Pattern:"mc",Color:11},{Pattern:"flo",Color:11},{Pattern:"bt",Color:11},{Pattern:"ms",Color:11},{Pattern:"mc",Color:11}]}',  # Australia,
    'AT': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:14},{Pattern:"ls",Color:14}]}',  # Austria,
    'AZ': 'minecraft:red_banner{Patterns:[{Pattern:"mc",Color:0},{Pattern:"bt",Color:14},{Pattern:"rs",Color:3},{Pattern:"ls",Color:13}]}',  # Azerbaijan,
    'BS': 'minecraft:yellow_banner{Patterns:[{Pattern:"rs",Color:9},{Pattern:"ls",Color:9},{Pattern:"tt",Color:15}]}',  # Bahamas,
    'BH': 'minecraft:red_banner{Patterns:[{Pattern:"ss",Color:0},{Pattern:"ts",Color:0},{Pattern:"hhb",Color:14}]}',  # Bahrain,
    'BD': 'minecraft:green_banner{Patterns:[{Pattern:"mc",Color:14}]}',  # Bangladesh,
    'BB': 'minecraft:yellow_banner{Patterns:[{Pattern:"flo",Color:15},{Pattern:"ms",Color:15},{Pattern:"rs",Color:4},{Pattern:"ts",Color:11},{Pattern:"bs",Color:11}]}',  # Barbados,
    'BY': 'minecraft:red_banner{Patterns:[{Pattern:"ls",Color:13},{Pattern:"tts",Color:0}]}',  # Belarus,
    'BE': 'minecraft:yellow_banner{Patterns:[{Pattern:"ts",Color:15},{Pattern:"bs",Color:14}]}',  # Belgium,
    'BZ': 'minecraft:blue_banner{Patterns:[{Pattern:"bo",Color:14},{Pattern:"tt",Color:11},{Pattern:"bt",Color:11},{Pattern:"mc",Color:5},{Pattern:"mc",Color:0}]}',  # Belize,
    'BJ': 'minecraft:red_banner{Patterns:[{Pattern:"vhr",Color:4},{Pattern:"ts",Color:13}]}',  # Benin,
    # 'BM': ''  # Bermuda,
    'BT': 'minecraft:orange_banner{Patterns:[{Pattern:"rud",Color:4},{Pattern:"mr",Color:0}]}',  # Bhutan,
    'BO': 'minecraft:yellow_banner{Patterns:[{Pattern:"ls",Color:13},{Pattern:"rs",Color:14}]}',  # Bolivia,
    'BA': 'minecraft:yellow_banner{Patterns:[{Pattern:"dls",Color:0},{Pattern:"ld",Color:11},{Pattern:"bo",Color:11}]}',  # Bosnia And Herzegovina,
    'BW': 'minecraft:white_banner{Patterns:[{Pattern:"sc",Color:15},{Pattern:"rs",Color:3},{Pattern:"ls",Color:3}]}',  # Botswana,
    # 'BV': ''  # Bouvet Island,
    'BR': 'minecraft:green_banner{Patterns:[{Pattern:"mr",Color:4},{Pattern:"mc",Color:11}]}',  # Brazil,
    # 'IO': ''  # British Indian Ocean Territory,
    'BN': 'minecraft:yellow_banner{Patterns:[{Pattern:"dls",Color:8},{Pattern:"mc",Color:14}]}',  # Brunei,
    'BG': 'minecraft:green_banner{Patterns:[{Pattern:"ls",Color:14},{Pattern:"rs",Color:0}]}',  # Bulgaria,
    'BF': 'minecraft:green_banner{Patterns:[{Pattern:"vhr",Color:14},{Pattern:"mc",Color:4}]}',  # Burkina Faso,
    'BI': 'minecraft:red_banner{Patterns:[{Pattern:"bt",Color:5},{Pattern:"tt",Color:5},{Pattern:"cr",Color:0},{Pattern:"mc",Color:0}]}',  # Burundi,
    'KH': 'minecraft:red_banner{Patterns:[{Pattern:"mr",Color:0},{Pattern:"rs",Color:11},{Pattern:"ls",Color:11}]}',  # Cambodia,
    'CM': 'minecraft:red_banner{Patterns:[{Pattern:"ts",Color:13},{Pattern:"bs",Color:4},{Pattern:"mc",Color:4}]}',  # Cameroon,
    'CA': 'minecraft:white_banner{Patterns:[{Pattern:"ts",Color:14},{Pattern:"bs",Color:14},{Pattern:"mc",Color:14}]}',  # Canada,
    'CV': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:11},{Pattern:"ls",Color:11},{Pattern:"cs",Color:14},{Pattern:"flo",Color:4},{Pattern:"mc",Color:14}]}',  # Cape Verde,
    # 'KY': ''  # Cayman Islands,
    'CF': 'minecraft:lime_banner{Patterns:[{Pattern:"ls",Color:4},{Pattern:"vhr",Color:0},{Pattern:"rs",Color:11},{Pattern:"ms",Color:14}]}',  # Central African Republic,
    'TD': 'minecraft:yellow_banner{Patterns:[{Pattern:"ts",Color:11},{Pattern:"bs",Color:14}]}',  # Chad,
    'CL': 'minecraft:white_banner{Patterns:[{Pattern:"ts",Color:11},{Pattern:"vh",Color:14}]}',  # Chile,
    'CN': 'minecraft:red_banner{Patterns:[{Pattern:"tr",Color:4},{Pattern:"bo",Color:14}]}',  # China,
    # 'CX': ''  # Christmas Island,
    # 'CC': ''  # Cocos (keeling) Islands,
    'CO': 'minecraft:yellow_banner{Patterns:[{Pattern:"vh",Color:11},{Pattern:"ls",Color:14}]}',  # Colombia,
    'KM': 'minecraft:red_banner{Patterns:[{Pattern:"vhr",Color:0},{Pattern:"rs",Color:4},{Pattern:"ls",Color:11},{Pattern:"tt",Color:13}]}',  # Comoros,
    'CG': 'minecraft:green_banner{Patterns:[{Pattern:"lud",Color:14},{Pattern:"drs",Color:4}]}',  # Congo,
    'CD': 'minecraft:blue_banner{Patterns:[{Pattern:"tr",Color:4},{Pattern:"bo",Color:11},{Pattern:"drs",Color:4},{Pattern:"drs",Color:14}]}',  # Congo, The Democratic Republic Of The,
    # 'CK': ''  # Cook Islands,
    'CR': 'minecraft:white_banner{Patterns:[{Pattern:"bo",Color:11},{Pattern:"cs",Color:14}]}',  # Costa Rica,
    'CI': 'minecraft:white_banner{Patterns:[{Pattern:"ts",Color:1},{Pattern:"bs",Color:13}]}',  # Cote D'ivoire,
    'HR': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:14},{Pattern:"ls",Color:11},{Pattern:"mc",Color:6}]}',  # Croatia,
    'CU': 'minecraft:white_banner{Patterns:[{Pattern:"bo",Color:11},{Pattern:"bt",Color:0},{Pattern:"cs",Color:11},{Pattern:"tt",Color:14}]}',  # Cuba,
    'CY': 'minecraft:white_banner{Patterns:[{Pattern:"flo",Color:13},{Pattern:"mc",Color:0},{Pattern:"vhr",Color:0},{Pattern:"mr",Color:1}]}',  # Cyprus,
    'CZ': 'minecraft:white_banner{Patterns:[{Pattern:"vh",Color:14},{Pattern:"tt",Color:11}]}',  # Czech Republic,
    'DK': 'minecraft:red_banner{Patterns:[{Pattern:"sc",Color:0}]}',  # Denmark,
    'DJ': 'minecraft:light_blue_banner{Patterns:[{Pattern:"vh",Color:5},{Pattern:"tt",Color:0}]}',  # Djibouti,
    'DM': 'minecraft:green_banner{Patterns:[{Pattern:"ms",Color:4},{Pattern:"cs",Color:4},{Pattern:"sc",Color:15},{Pattern:"mc",Color:14}]}',  # Dominica,
    'DO': 'minecraft:blue_banner{Patterns:[{Pattern:"vh",Color:14},{Pattern:"hhb",Color:14},{Pattern:"bl",Color:11},{Pattern:"ms",Color:0},{Pattern:"cs",Color:0},{Pattern:"mc",Color:5}]}',  # Dominican Republic,
    'TP': 'minecraft:red_banner{Patterns:[{Pattern:"tt",Color:4},{Pattern:"tts",Color:15}]}',  # East Timor,
    'EC': 'minecraft:yellow_banner{Patterns:[{Pattern:"vh",Color:11},{Pattern:"ls",Color:14},{Pattern:"mc",Color:3}]}',  # Ecuador,
    'EG': 'minecraft:white_banner{Patterns:[{Pattern:"mc",Color:4},{Pattern:"ls",Color:15},{Pattern:"rs",Color:14}]}',  # Egypt,
    'SV': 'minecraft:white_banner{Patterns:[{Pattern:"mc",Color:13},{Pattern:"rs",Color:11},{Pattern:"ls",Color:11}]}',  # El Salvador,
    'GQ': 'minecraft:white_banner{Patterns:[{Pattern:"ls",Color:14},{Pattern:"rs",Color:13},{Pattern:"tt",Color:9}]}',  # Equatorial Guinea,
    'ER': 'minecraft:lime_banner{Patterns:[{Pattern:"vh",Color:9},{Pattern:"tt",Color:14},{Pattern:"cs",Color:14}]}',  # Eritrea,
    'EE': 'minecraft:black_banner{Patterns:[{Pattern:"rs",Color:11},{Pattern:"ls",Color:0}]}',  # Estonia,
	'SZ': 'minecraft:yellow_banner{Patterns:[{Pattern:"cs",Color:14},{Pattern:"ls",Color:11},{Pattern:"rs",Color:11},{Pattern:"mr",Color:8}]}',  # Eswatini,
    'ET': 'minecraft:yellow_banner{Patterns:[{Pattern:"rs",Color:13},{Pattern:"ls",Color:14},{Pattern:"mc",Color:11}]}',  # Ethiopia,
    # 'FK': ''  # Falkland Islands (malvinas),
    # 'FO': ''  # Faroe Islands,
    'FJ': 'minecraft:light_blue_banner{Patterns:[{Pattern:"hhb",Color:14},{Pattern:"bo",Color:3},{Pattern:"ms",Color:3},{Pattern:"tr",Color:11}]}',  # Fiji,
    'FI': 'minecraft:white_banner{Patterns:[{Pattern:"ms",Color:11},{Pattern:"cs",Color:11}]}',  # Finland,
    'FR': 'minecraft:white_banner{Patterns:[{Pattern:"ts",Color:11},{Pattern:"bs",Color:14}]}',  # France,
    # 'GF': ''  # French Guiana,
    # 'PF': ''  # French Polynesia,
    # 'TF': ''  # French Southern Territories,
    'GA': 'minecraft:yellow_banner{Patterns:[{Pattern:"rs",Color:13},{Pattern:"ls",Color:9}]}',  # Gabon,
    'GM': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:14},{Pattern:"ls",Color:13},{Pattern:"cs",Color:11}]}',  # Gambia,
    'GE': 'minecraft:red_banner{Patterns:[{Pattern:"bo",Color:0},{Pattern:"cs",Color:0},{Pattern:"ms",Color:0},{Pattern:"sc",Color:14}]}',  # Georgia,
    'DE': 'minecraft:red_banner{Patterns:[{Pattern:"rs",Color:15},{Pattern:"ls",Color:4}]}',  # Germany,
    'GH': 'minecraft:yellow_banner{Patterns:[{Pattern:"ls",Color:13},{Pattern:"rs",Color:14},{Pattern:"mc",Color:15}]}',  # Ghana,
    # 'GI': ''  # Gibraltar,
    'GR': 'minecraft:light_blue_banner{Patterns:[{Pattern:"ss",Color:0},{Pattern:"tr",Color:3}]}',  # Greece,
    # 'GL': ''  # Greenland,
    'GD': 'minecraft:yellow_banner{Patterns:[{Pattern:"bt",Color:13},{Pattern:"tt",Color:13},{Pattern:"bo",Color:14}]}',  # Grenada,
    # 'GP': ''  # Guadeloupe,
    # 'GU': ''  # Guam,
    'GT': 'minecraft:white_banner{Patterns:[{Pattern:"mc",Color:5},{Pattern:"ts",Color:3},{Pattern:"bs",Color:3}]}',  # Guatemala,
    'GN': 'minecraft:yellow_banner{Patterns:[{Pattern:"ts",Color:14},{Pattern:"bs",Color:13}]}',  # Guinea,
    'GW': 'minecraft:green_banner{Patterns:[{Pattern:"vhr",Color:4},{Pattern:"ts",Color:14}]}',  # Guinea-bissau,
    'GY': 'minecraft:green_banner{Patterns:[{Pattern:"cs",Color:4},{Pattern:"tt",Color:14}]}',  # Guyana,
    'HT': 'minecraft:blue_banner{Patterns:[{Pattern:"vh",Color:14},{Pattern:"mc",Color:0}]}',  # Haiti,
    # 'HM': ''  # Heard Island And Mcdonald Islands,
    'HN': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:11},{Pattern:"ls",Color:11}]}',  # Honduras,
    'HK': 'minecraft:red_banner{Patterns:[{Pattern:"flo",Color:0}]}',  # Hong Kong,
    'HU': 'minecraft:white_banner{Patterns:[{Pattern:"ls",Color:13},{Pattern:"rs",Color:14}]}',  # Hungary,
    'IS': 'minecraft:blue_banner{Patterns:[{Pattern:"cs",Color:0},{Pattern:"ms",Color:0},{Pattern:"sc",Color:14}]}',  # Iceland,
    'IN': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:1},{Pattern:"ls",Color:13},{Pattern:"mc",Color:3}]}',  # India,
    'ID': 'minecraft:white_banner{Patterns:[{Pattern:"vhr",Color:14}]}',  # Indonesia,
    'IR': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:13},{Pattern:"ls",Color:14},{Pattern:"mc",Color:0},{Pattern:"mc",Color:14}]}',  # Iran,
    'IQ': 'minecraft:white_banner{Patterns:[{Pattern:"mr",Color:13},{Pattern:"rs",Color:14},{Pattern:"ls",Color:15}]}',  # Iraq,
    'IE': 'minecraft:white_banner{Patterns:[{Pattern:"ts",Color:13},{Pattern:"bs",Color:1}]}',  # Ireland,
    'IL': 'minecraft:white_banner{Patterns:[{Pattern:"mc",Color:11},{Pattern:"rs",Color:11},{Pattern:"ls",Color:11},{Pattern:"bo",Color:0}]}',  # Israel,
    'IT': 'minecraft:white_banner{Patterns:[{Pattern:"ts",Color:13},{Pattern:"bs",Color:14}]}',  # Italy,
    'JM': 'minecraft:green_banner{Patterns:[{Pattern:"bt",Color:15},{Pattern:"tt",Color:15},{Pattern:"cr",Color:4}]}',  # Jamaica,
    'JP': 'minecraft:white_banner{Patterns:[{Pattern:"mc",Color:14}]}',  # Japan,
    'JO': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:15},{Pattern:"ls",Color:13},{Pattern:"tt",Color:14}]}',  # Jordan,
    'KZ': 'minecraft:light_blue_banner{Patterns:[{Pattern:"flo",Color:4},{Pattern:"rs",Color:3},{Pattern:"ts",Color:4}]}',  # Kazakhstan,
    'KE': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:15},{Pattern:"ls",Color:13},{Pattern:"cs",Color:14},{Pattern:"mc",Color:0},{Pattern:"mc",Color:14}]}',  # Kenya,
    'KI': 'minecraft:red_banner{Patterns:[{Pattern:"flo",Color:4},{Pattern:"vh",Color:0},{Pattern:"ls",Color:11}]}',  # Kiribati,
    'KV': 'minecraft:blue_banner{Patterns:[{Pattern:"flo",Color:0},{Pattern:"vh",Color:11},{Pattern:"mr",Color:4}]}',  # Kosovo,
    'KW': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:13},{Pattern:"ls",Color:14},{Pattern:"tt",Color:15}]}',  # Kuwait,
    'KG': 'minecraft:red_banner{Patterns:[{Pattern:"flo",Color:4}]}',  # Kyrgyzstan,
    'LA': 'minecraft:blue_banner{Patterns:[{Pattern:"rs",Color:14},{Pattern:"ls",Color:14},{Pattern:"mc",Color:0}]}',  # Laos,
    'LV': 'minecraft:brown_banner{Patterns:[{Pattern:"cs",Color:0}]}',  # Latvia,
    'LB': 'minecraft:white_banner{Patterns:[{Pattern:"flo",Color:13},{Pattern:"rs",Color:14},{Pattern:"ls",Color:14}]}',  # Lebanon,
    'LS': 'minecraft:white_banner{Patterns:[{Pattern:"ms",Color:15},{Pattern:"rs",Color:11},{Pattern:"ls",Color:13}]}',  # Lesotho,
    'LR': 'minecraft:red_banner{Patterns:[{Pattern:"ss",Color:0},{Pattern:"tr",Color:11}]}',  # Liberia,
    'LY': 'minecraft:black_banner{Patterns:[{Pattern:"mc",Color:0},{Pattern:"bt",Color:15},{Pattern:"rs",Color:14},{Pattern:"ls",Color:13}]}',  # Libya,
    'LI': 'minecraft:blue_banner{Patterns:[{Pattern:"tr",Color:4},{Pattern:"bo",Color:11},{Pattern:"cs",Color:11},{Pattern:"vh",Color:14}]}',  # Liechtenstein,
    'LT': 'minecraft:green_banner{Patterns:[{Pattern:"rs",Color:4},{Pattern:"ls",Color:14}]}',  # Lithuania,
    'LU': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:14},{Pattern:"ls",Color:3}]}',  # Luxembourg,
    # 'MO': ''  # Macau,
    'MK': 'minecraft:red_banner{Patterns:[{Pattern:"sc",Color:4},{Pattern:"cr",Color:4},{Pattern:"mc",Color:14},{Pattern:"mc",Color:4}]}',  # Macedonia (North),
    'MG': 'minecraft:green_banner{Patterns:[{Pattern:"vhr",Color:14},{Pattern:"ts",Color:0}]}',  # Madagascar,
    'MW': 'minecraft:black_banner{Patterns:[{Pattern:"flo",Color:14},{Pattern:"cs",Color:14},{Pattern:"ls",Color:13}]}',  # Malawi,
    'MY': 'minecraft:red_banner{Patterns:[{Pattern:"ss",Color:0},{Pattern:"tr",Color:11}]}',  # Malaysia,
    'MV': 'minecraft:green_banner{Patterns:[{Pattern:"mc",Color:0},{Pattern:"bt",Color:13},{Pattern:"bo",Color:14}]}',  # Maldives,
    'ML': 'minecraft:yellow_banner{Patterns:[{Pattern:"ts",Color:5},{Pattern:"bs",Color:14}]}',  # Mali,
    'MT': 'minecraft:white_banner{Patterns:[{Pattern:"tr",Color:8},{Pattern:"bo",Color:0},{Pattern:"hhb",Color:14}]}',  # Malta,
    'MH': 'minecraft:blue_banner{Patterns:[{Pattern:"tr",Color:0},{Pattern:"bo",Color:11},{Pattern:"cs",Color:1},{Pattern:"vh",Color:0},{Pattern:"ls",Color:11}]}',  # Marshall Islands,
    # 'MQ': ''  # Martinique,
    'MR': 'minecraft:green_banner{Patterns:[{Pattern:"mc",Color:4},{Pattern:"rs",Color:14},{Pattern:"ls",Color:14}]}',  # Mauritania,
    'MU': 'minecraft:blue_banner{Patterns:[{Pattern:"vh",Color:4},{Pattern:"rs",Color:14},{Pattern:"ls",Color:13}]}',  # Mauritius,
    # 'YT': ''  # Mayotte,
    'MX': 'minecraft:white_banner{Patterns:[{Pattern:"flo",Color:5},{Pattern:"vhr",Color:0},{Pattern:"mc",Color:12},{Pattern:"ts",Color:13},{Pattern:"bs",Color:14}]}',  # Mexico,
    'FM': 'minecraft:light_blue_banner{Patterns:[{Pattern:"mr",Color:0},{Pattern:"cr",Color:3}]}',  # Micronesia, Federated States Of,
    'MD': 'minecraft:yellow_banner{Patterns:[{Pattern:"mc",Color:15},{Pattern:"ts",Color:11},{Pattern:"bs",Color:14}]}',  # Moldova, Republic Of,
    'MC': 'minecraft:red_banner{Patterns:[{Pattern:"vh",Color:0}]}',  # Monaco,
    'MN': 'minecraft:blue_banner{Patterns:[{Pattern:"ts",Color:14},{Pattern:"bs",Color:14}]}',  # Mongolia,
    # 'MS': ''  # Montserrat,
    'ME': 'minecraft:red_banner{Patterns:[{Pattern:"bo",Color:1},{Pattern:"mc",Color:1}]}',  # Montenegro,
    'MA': 'minecraft:red_banner{Patterns:[{Pattern:"mc",Color:13}]}',  # Morocco,
    'MZ': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:13},{Pattern:"ls",Color:4},{Pattern:"cs",Color:15},{Pattern:"tt",Color:14}]}',  # Mozambique,
    'MM': 'minecraft:lime_banner{Patterns:[{Pattern:"rs",Color:4},{Pattern:"ls",Color:14},{Pattern:"mc",Color:0}]}',  # Myanmar,
    'NA': 'minecraft:blue_banner{Patterns:[{Pattern:"tr",Color:4},{Pattern:"bo",Color:11},{Pattern:"lud",Color:13},{Pattern:"drs",Color:0},{Pattern:"drs",Color:14}]}',  # Namibia,
    'NR': 'minecraft:blue_banner{Patterns:[{Pattern:"tl",Color:0},{Pattern:"bo",Color:11},{Pattern:"cs",Color:11},{Pattern:"cs",Color:4}]}',  # Nauru,
    'NP': 'minecraft:white_banner{Patterns:[{Pattern:"hh",Color:11},{Pattern:"ts",Color:14}]}',  # Nepal,
    'NL': 'minecraft:white_banner{Patterns:[{Pattern:"ls",Color:11},{Pattern:"rs",Color:14}]}',  # Netherlands,
    # 'AN': ''  # Netherlands Antilles,
    # 'NC': ''  # New Caledonia,
    'NZ': 'minecraft:black_banner{Patterns:[{Pattern:"drs",Color:0},{Pattern:"lud",Color:11}]}',  # New Zealand,
    'NI': 'minecraft:white_banner{Patterns:[{Pattern:"cs",Color:5},{Pattern:"bt",Color:0},{Pattern:"tt",Color:0},{Pattern:"rs",Color:11},{Pattern:"ls",Color:11}]}',  # Nicaragua,
    'NE': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:1},{Pattern:"ls",Color:5},{Pattern:"mc",Color:0},{Pattern:"mc",Color:1}]}',  # Niger,
    'NG': 'minecraft:white_banner{Patterns:[{Pattern:"ts",Color:13},{Pattern:"bs",Color:13}]}',  # Nigeria,
    # 'NU': ''  # Niue,
    # 'NF': ''  # Norfolk Island,
    # 'MP': ''  # Northern Mariana Islands,
	'KP': 'minecraft:red_banner{Patterns:[{Pattern:"rs",Color:0},{Pattern:"ls",Color:0},{Pattern:"rs",Color:11},{Pattern:"ls",Color:11},{Pattern:"mc",Color:0}]}',  # North Korea,
    'NO': 'minecraft:red_banner{Patterns:[{Pattern:"cs",Color:0},{Pattern:"ms",Color:0},{Pattern:"sc",Color:11}]}',  # Norway,
    'OM': 'minecraft:red_banner{Patterns:[{Pattern:"rs",Color:0},{Pattern:"ls",Color:13},{Pattern:"ts",Color:14}]}',  # Oman,
    'PK': 'minecraft:green_banner{Patterns:[{Pattern:"ts",Color:0},{Pattern:"mc",Color:0},{Pattern:"bt",Color:13}]}',  # Pakistan,
    'PW': 'minecraft:light_blue_banner{Patterns:[{Pattern:"mc",Color:4}]}',  # Palau,
    'PS': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:15},{Pattern:"ls",Color:13},{Pattern:"tt",Color:14}]}',  # Palestinian Territory,
    'PA': 'minecraft:white_banner{Patterns:[{Pattern:"hh",Color:14},{Pattern:"vhr",Color:11},{Pattern:"tr",Color:0}]}',  # Panama,
    'PG': 'minecraft:yellow_banner{Patterns:[{Pattern:"dls",Color:14},{Pattern:"bo",Color:14},{Pattern:"ld",Color:15}]}',  # Papua New Guinea,
    'PY': 'minecraft:white_banner{Patterns:[{Pattern:"mc",Color:5},{Pattern:"rs",Color:14},{Pattern:"ls",Color:11}]}',  # Paraguay,
    'PE': 'minecraft:white_banner{Patterns:[{Pattern:"ts",Color:14},{Pattern:"bs",Color:14}]}',  # Peru,
    'PH': 'minecraft:blue_banner{Patterns:[{Pattern:"vh",Color:14},{Pattern:"tt",Color:0}]}',  # Philippines,
    # 'PN': ''  # Pitcairn,
    'PL': 'minecraft:white_banner{Patterns:[{Pattern:"vh",Color:14}]}',  # Poland,
    'PT': 'minecraft:red_banner{Patterns:[{Pattern:"ts",Color:13},{Pattern:"mr",Color:4},{Pattern:"hhb",Color:14}]}',  # Portugal,
    # 'PR': ''  # Puerto Rico,
    'QA': 'minecraft:brown_banner{Patterns:[{Pattern:"ss",Color:0},{Pattern:"hhb",Color:12},{Pattern:"ts",Color:0}]}',  # Qatar,
    # 'RE': ''  # Reunion,
    'RO': 'minecraft:yellow_banner{Patterns:[{Pattern:"ts",Color:11},{Pattern:"bs",Color:14}]}',  # Romania,
    'RU': 'minecraft:blue_banner{Patterns:[{Pattern:"ls",Color:14},{Pattern:"rs",Color:0}]}',  # Russia,
    'RW': 'minecraft:light_blue_banner{Patterns:[{Pattern:"br",Color:4},{Pattern:"bo",Color:3},{Pattern:"cs",Color:3},{Pattern:"vh",Color:4},{Pattern:"ls",Color:13}]}',  # Rwanda,
    # 'SH': ''  # Saint Helena,
    'KN': 'minecraft:green_banner{Patterns:[{Pattern:"lud",Color:14},{Pattern:"drs",Color:4},{Pattern:"drs",Color:15}]}',  # Saint Kitts And Nevis,
    'LC': 'minecraft:black_banner{Patterns:[{Pattern:"vh",Color:4},{Pattern:"bo",Color:3},{Pattern:"ts",Color:3},{Pattern:"bs",Color:3}]}',  # Saint Lucia,
    # 'PM': ''  # Saint Pierre And Miquelon,
    'VC': 'minecraft:yellow_banner{Patterns:[{Pattern:"mr",Color:13},{Pattern:"cr",Color:4},{Pattern:"ts",Color:11},{Pattern:"bs",Color:13}]}',  # Saint Vincent And The Grenadines,
    'WS': 'minecraft:red_banner{Patterns:[{Pattern:"tr",Color:11}]}',  # Samoa,
    'SM': 'minecraft:light_blue_banner{Patterns:[{Pattern:"vhr",Color:0},{Pattern:"flo",Color:13},{Pattern:"rs",Color:0},{Pattern:"mc",Color:12}]}',  # San Marino,
    'ST': 'minecraft:black_banner{Patterns:[{Pattern:"ts",Color:4},{Pattern:"ms",Color:4},{Pattern:"bs",Color:4},{Pattern:"rs",Color:5},{Pattern:"ls",Color:5},{Pattern:"tts",Color:14}]}',  # Sao Tome And Principe,
    'SA': 'minecraft:green_banner{Patterns:[{Pattern:"sku",Color:0},{Pattern:"moj",Color:0},{Pattern:"ls",Color:13},{Pattern:"cs",Color:13}]}',  # Saudi Arabia,
    'SN': 'minecraft:yellow_banner{Patterns:[{Pattern:"ts",Color:13},{Pattern:"bs",Color:14},{Pattern:"mc",Color:13}]}',  # Senegal,
    'RS': 'minecraft:red_banner{Patterns:[{Pattern:"flo",Color:4},{Pattern:"cs",Color:11},{Pattern:"ls",Color:0},{Pattern:"mc",Color:14}]}',  # Serbia,
    'SC': 'minecraft:yellow_banner{Patterns:[{Pattern:"rs",Color:11},{Pattern:"vh",Color:0},{Pattern:"ls",Color:13},{Pattern:"drs",Color:14}]}',  # Seychelles,
    'SL': 'minecraft:white_banner{Patterns:[{Pattern:"ls",Color:3},{Pattern:"rs",Color:5}]}',  # Sierra Leone,
    'SG': 'minecraft:red_banner{Patterns:[{Pattern:"tr",Color:0},{Pattern:"cs",Color:14},{Pattern:"bo",Color:14},{Pattern:"vh",Color:0}]}',  # Singapore,
    'SK': 'minecraft:blue_banner{Patterns:[{Pattern:"ls",Color:14},{Pattern:"rs",Color:0},{Pattern:"mc",Color:0},{Pattern:"mc",Color:14}]}',  # Slovakia,
    'SI': 'minecraft:blue_banner{Patterns:[{Pattern:"ls",Color:14},{Pattern:"rs",Color:0},{Pattern:"mc",Color:0},{Pattern:"mc",Color:11}]}',  # Slovenia,
    'SB': 'minecraft:blue_banner{Patterns:[{Pattern:"tr",Color:0},{Pattern:"cs",Color:11},{Pattern:"bo",Color:11},{Pattern:"lud",Color:13},{Pattern:"drs",Color:4}]}',  # Solomon Islands,
    'SO': 'minecraft:cyan_banner{Patterns:[{Pattern:"mc",Color:0}]}',  # Somalia,
    'ZA': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:14},{Pattern:"ls",Color:11},{Pattern:"cs",Color:13},{Pattern:"tt",Color:15}]}',  # South Africa,
	'KR':'minecraft:red_banner{BlockEntityTag:{Patterns:[{Pattern:lud,Color:11},{Pattern:ts,Color:0},{Pattern:bs,Color:0},{Pattern:cbo,Color:0},{Pattern:bts,Color:15},{Pattern:tts,Color:15},{Pattern:bo,Color:0}]}}',  # South Korea,
    'SS': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:15},{Pattern:"ls",Color:13},{Pattern:"cs",Color:14},{Pattern:"tt",Color:11}]}',  # South Sudan,
    'ES': 'minecraft:yellow_banner{Patterns:[{Pattern:"tt",Color:14},{Pattern:"ts",Color:4},{Pattern:"rs",Color:14},{Pattern:"ls",Color:14}]}',  # Spain,
    'LK': 'minecraft:red_banner{Patterns:[{Pattern:"mr",Color:4},{Pattern:"ms",Color:14},{Pattern:"hh",Color:1},{Pattern:"ts",Color:13},{Pattern:"bo",Color:4}]}',  # Sri Lanka,
    'SD': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:14},{Pattern:"ls",Color:15},{Pattern:"tt",Color:13}]}',  # Sudan,
    'SR': 'minecraft:white_banner{Patterns:[{Pattern:"bo",Color:13},{Pattern:"cs",Color:14},{Pattern:"mc",Color:4}]}',  # Suriname,
    # 'SJ': ''  # Svalbard And Jan Mayen,
    'SE': 'minecraft:blue_banner{Patterns:[{Pattern:"cs",Color:4},{Pattern:"ms",Color:4}]}',  # Sweden,
    'CH': 'minecraft:red_banner{Patterns:[{Pattern:"ms",Color:0},{Pattern:"cs",Color:0},{Pattern:"bo",Color:14},{Pattern:"ts",Color:14},{Pattern:"bs",Color:14}]}',  # Switzerland,
    'SY': 'minecraft:green_banner{Patterns:[{Pattern:"ts",Color:0},{Pattern:"bs",Color:0},{Pattern:"ms",Color:0},{Pattern:"rs",Color:14},{Pattern:"ls",Color:15}]}',  # Syrian Arab Republic,
    'TW': 'minecraft:red_banner{Patterns:[{Pattern:"tr",Color:11}]}',  # Taiwan,
    'TJ': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:14},{Pattern:"ls",Color:13},{Pattern:"mc",Color:4}]}',  # Tajikistan,
    'TZ': 'minecraft:lime_banner{Patterns:[{Pattern:"lud",Color:3},{Pattern:"drs",Color:15}]}',  # Tanzania, United Republic Of,
    'TH': 'minecraft:white_banner{Patterns:[{Pattern:"bo",Color:14},{Pattern:"cs",Color:11}]}',  # Thailand,
    'TG': 'minecraft:yellow_banner{Patterns:[{Pattern:"bo",Color:13},{Pattern:"bt",Color:4},{Pattern:"tt",Color:4},{Pattern:"cs",Color:13},{Pattern:"tr",Color:14}]}',  # Togo,
    # 'TK': ''  # Tokelau,
    'TO': 'minecraft:red_banner{Patterns:[{Pattern:"bo",Color:0},{Pattern:"sc",Color:0},{Pattern:"vh",Color:14},{Pattern:"hhb",Color:14}]}',  # Tonga,
    'TT': 'minecraft:red_banner{Patterns:[{Pattern:"dls",Color:15}]}',  # Trinidad And Tobago,
    'TN': 'minecraft:red_banner{Patterns:[{Pattern:"mr",Color:0},{Pattern:"mc",Color:14}]}',  # Tunisia,
    'TR': 'minecraft:red_banner{Patterns:[{Pattern:"mr",Color:0},{Pattern:"mc",Color:14},{Pattern:"bt",Color:14}]}',  # Turkey,
    'TM': 'minecraft:green_banner{Patterns:[{Pattern:"hh",Color:14},{Pattern:"ts",Color:13}]}',  # Turkmenistan,
    # 'TC': ''  # Turks And Caicos Islands,
    'TV': 'minecraft:blue_banner{Patterns:[{Pattern:"dls",Color:0},{Pattern:"cr",Color:14},{Pattern:"vh",Color:9},{Pattern:"hhb",Color:9}]}',  # Tuvalu,
    'UG': 'minecraft:yellow_banner{Patterns:[{Pattern:"rs",Color:15},{Pattern:"ls",Color:14},{Pattern:"mc",Color:0}]}',  # Uganda,
    'UA': 'minecraft:blue_banner{Patterns:[{Pattern:"vh",Color:4}]}',  # Ukraine,
    'AE': 'minecraft:white_banner{Patterns:[{Pattern:"rs",Color:13},{Pattern:"ls",Color:15},{Pattern:"ts",Color:14}]}',  # United Arab Emirates,
    'GB': 'minecraft:blue_banner{Patterns:[{Pattern:"drs",Color:0},{Pattern:"dls",Color:0},{Pattern:"cr",Color:14},{Pattern:"cs",Color:0},{Pattern:"ms",Color:0},{Pattern:"sc",Color:14}]}',  # United Kingdom,
	'UK': 'minecraft:blue_banner{Patterns:[{Pattern:"drs",Color:0},{Pattern:"dls",Color:0},{Pattern:"cr",Color:14},{Pattern:"cs",Color:0},{Pattern:"ms",Color:0},{Pattern:"sc",Color:14}]}',  # United Kingdom,
    'US': 'minecraft:red_banner{Patterns:[{Pattern:"ss",Color:0},{Pattern:"tr",Color:11}]}',  # United States,
    # 'UM': ''  # United States Minor Outlying Islands,
    'UY': 'minecraft:white_banner{Patterns:[{Pattern:"ss",Color:11},{Pattern:"tr",Color:4}]}',  # Uruguay,
    'UZ': 'minecraft:red_banner{Patterns:[{Pattern:"rs",Color:3},{Pattern:"ls",Color:5},{Pattern:"cs",Color:0}]}',  # Uzbekistan,
    'VU': 'minecraft:green_banner{Patterns:[{Pattern:"vhr",Color:14},{Pattern:"tt",Color:15}]}',  # Vanuatu,
    'VA': 'minecraft:white_banner{Patterns:[{Pattern:"hhb",Color:8},{Pattern:"ls",Color:0},{Pattern:"rs",Color:0},{Pattern:"ms",Color:0},{Pattern:"bts",Color:0},{Pattern:"hh",Color:4}]}',  # Vatican City,
	'VE': 'minecraft:blue_banner{Patterns:[{Pattern:"flo",Color:0},{Pattern:"rs",Color:4},{Pattern:"ls",Color:14}]}',  # Venezuela,
    'VN': 'minecraft:red_banner{Patterns:[{Pattern:"mc",Color:4}]}',  # Vietnam,
    # 'VG': ''  # Virgin Islands, British,
    # 'VI': ''  # Virgin Islands, U.s.,
    # 'WF': ''  # Wallis And Futuna,
    # 'EH': ''  # Western Sahara,
    'YE': 'minecraft:white_banner{Patterns:[{Pattern:"ls",Color:15},{Pattern:"rs",Color:14}]}',  # Yemen,
    'ZM': 'minecraft:green_banner{Patterns:[{Pattern:"hhb",Color:14},{Pattern:"bs",Color:15},{Pattern:"bts",Color:1},{Pattern:"rs",Color:13}]}',  # Zambia,
    'ZW': 'minecraft:red_banner{Patterns:[{Pattern:"cs",Color:15},{Pattern:"rs",Color:4},{Pattern:"ls",Color:4},{Pattern:"bo",Color:13},{Pattern:"tt",Color:0}]}',  # Zimbabwe,
}